### ISSUE TITLE
last isn't invalid

### ISSUE THREAD

**Issue by Cynosphere** [DaaOtt/sniffer#2]
Attempted to run Nethack and it gave me this error and prints last isn't invalid on messages

[ERROR] addons/nethack/lua/nethack.lua:103: attempt to get length of local 'last' (a nil value)

**Comment by Kefta** [comment]
```
if outgoingName and msgSettings[outgoingName] and msgSettings[outgoingName].sout then return end
            logWrite(netTypes[i], val, ...)
```

Seems like last will always be nil since outgoingName is going to be nil when that function is run

**Comment by ottworks** [comment]
Might be fixed with recent commits, does the issue persist?

**Comment by ottworks** [comment]
Fixed
